### ISSUE TITLE
Missing commands 

### ISSUE THREAD

**Issue by Pixalesce** [richardwesthaver/org-notion#4]
Hi, 

I'm super excited to use this package to integrate my Notion notes into the goodness of Emacs and org-mode. However, I am having trouble getting started. 

The steps I have taken so far are as follows:
1. install package
2. create Notion integration
3. create a new .org file
4. enable org-notion mode
>5. execute org-notion-pull

At this point, I find that `org-notion-pull` is not a command that is available for use (I looked for it via `M-x`, and double checked via `C-h k C-c n f`), same for `org-notion-push`. 

I then tried running the other commands that I'm able to find, and found that `org-notion-get-current-user` returns my correct username, and `org-notion-browse` does indeed bring me to the correct page when I paste in the correct url path.

Other commands also return errors, such as `org-notion-get-page` and `org-notion-get-user` returning this similar error.

```
Wrong number of arguments: ((t) (id) "Get page (or user) with given ID from workspace." (interactive) (org-notion-dispatch (org-notion-request :method 'page :data id :callback #'(lambda (_response) (save-current-buffer (set-buffer (current-buffer)) (search-forward "

") (let ((json-data (json-read))) (setq org-notion-last-dispatch-result json-data) (org-notion--handle-http-error json-data) (if (equal (cdr ...) "page") (progn (org-notion-from-json ... json-data))))))))), 0
```

Can you assist me with this please? I would love to be able to fully utilise this tool!

**Comment by richardwesthaver** [comment]
hello @Pixalesce , unfortunately I haven't had much time to work on this and it's quite low on my priority list.

- push/pull are not implemented as you noted
- get-page not implemented, get-user just fixed with default of (oref org-notion-current-user :id)

there is some work to be done but you can check the source of those functions which shows how the low-level API is called with (org-notion-dispatch (org-notion-request ... :callback (org-notion-with-callback ...)))
